### ISSUE TITLE
format document sometimes ignored

### ISSUE THREAD

**Issue by jonathandturner** [rust-lang-nursery/rls-vscode#65] opened 2017-06-21 04:08 UTC
I have two files in my project, main.rs and other.rs.

If I do 'format document' on my other.rs, it works fine.  If, instead, I do format document on my main.rs, it doesn't do anything and leaves the file as is (complete with trailing spaces).

**Comment by jonathandturner** [comment] 2017-06-21 18:22
Looking at the "Rust Language Server" output, I get:

```
[Error - 6:21:09 AM] Request textDocument/formatting failed.
  Message: Reformat failed to complete successfully
  Code: -32601
```

As this file builds correctly, not sure what would fail formatting.

**Comment by doxxx** [comment] 2017-07-25 21:48
@jonathandturner I've had that happen where some of the lines in the file exceeded the default mad_width setting of 100 in the rustfmt settings. I worked around the problem by creating a `rustfmt.toml` file in the root of my project and adding `max_width = 120` to it.

**Comment by nrc** [comment] 2017-07-25 22:14
Ah, that's an interesting clue - rustfmt is meant to work as a checker too, so if a line fails the width constraint it sets the exit code to a failure code. I wonder if the RLS is interpreting that as failure to run.

**Comment by doxxx** [comment] 2017-07-25 22:24
When I use the VSCode Format Document command on a file that is already formatted, I get no error. If I add a line with just comment characters that exceeds the max_width setting in my rustfmt.toml by two, I get this error:

```
[Error - 6:23:00 PM] Request textDocument/formatting failed.
  Message: Reformat failed to complete successfully
  Code: -32603 
```

**Comment by doxxx** [comment] 2017-07-25 22:37
rustfmt reports the error reasonably well:

```
Rustfmt failed at \\?\C:\Users\Gordon\dev\rust\raytracer\src\object.rs:13: line exceeded maximum length (maximum: 120, found: 121) (sorry)
```

But I guess rls doesn't parse that and just looks at the exit code.

**Comment by doxxx** [comment] 2017-07-25 22:38
IMHO, linters and formatters should be separate tools. rustfmt should be reformatting the file to _achieve_ the max_width setting, not simply aborting when a line exceeds that max.

**Comment by doxxx** [comment] 2017-07-25 23:30
I take that back. It seems to only fail with that error when it can't reformat the line to reduce it below max_width. If I make a fn declaration with a long list of parameters that extends past the max_width, rustfmt will reformat the declaration to chop down, without reporting that error.

**Comment by nrc** [comment] 2017-10-30 05:22
cc https://github.com/rust-lang-nursery/rustfmt/issues/1977 (because we seem to need to check the exit code better in the RLS)

**Comment by DanielJoyce** [comment] 2018-04-15 04:06
Not only does the format fail, RLS crashes and rls-vscode fails to restart it.

At the very least can that bit be made robust?

**Comment by nrc** [comment] 2018-04-16 03:00
@DanielJoyce do you have a test case which reproduces this reliably? I'd like to look into this.

**Comment by nrc** [comment] 2018-06-21 03:33
This should be fixed now that we've changed the rustfmt exit codes.

**Closed by nrc** 2018-06-21 03:33 UTC
Labels: P-High
