### ISSUE TITLE
Mismatched function return type shows error diagnostic in the whole function

### ISSUE THREAD

**Issue by joaomoreno** [rust-lang-nursery/rls-vscode#301] opened 2018-04-25 10:20 UTC
The following function fails to return its described return type:

```rust
fn foo() -> u32 {
	println!("ok");
}
```

Ideally, there should be an error decoration under the function's name, or possibly its return type. Currently the decoration spans the entire function implementation, which makes it very hard to notice other error decorations:

![image](https://user-images.githubusercontent.com/22350/39240013-e3ce4328-4882-11e8-89ad-84600d9ee17f.png)

**Comment by nrc** [comment] 2018-04-30 02:02
We are just using the span from the compiler, so we don't get to choose where we put the squiggle. I agree this seems not great though (and I think it would be not great in the compiler without an IDE too).

cc @estebank 

I'm closing this issue since it is a compiler issue, but we might look at opening a compiler issue to fix this.

**Closed by nrc** 2018-04-30 02:02 UTC

**Comment by estebank** [comment] 2018-04-30 04:35
I believe this would be covered by https://github.com/rust-lang/rust/issues/50009.

Out of curiosity (as I don't use VSCode at the moment), are you displaying secondary spans at all? I intend to change the diagnostic to point at the last line of the scope (in this case `println!("ok")`), but for real code where the scope would be large, maybe even longer than the screen can show, the function signature might be too far away from the primary span, making it harder to see what the problem is.

**Comment by nrc** [comment] 2018-04-30 04:53
> I believe this would be covered by rust-lang/rust#50009.

Awesome!

>  are you displaying secondary spans at all? 

Currently, no, but @Xanewok has been working on adding that now that there is support in VSCode.

**Comment by estebank** [comment] 2018-04-30 05:01
That sounds great. I'll have to sit down and think about some better wording for this diagnostic, maybe even adding a new error code (or extend [E0069](https://doc.rust-lang.org/error-index.html#E0069)) with text along the lines of "function body does not return a value of type RETURN_TYPE". That way it wouldn't break expectations when pointing at the function signature when complaining about the body as much as if we were to use the same `type mismatch` error code.
