### ISSUE TITLE
RLS builds the 'debug' target instead of 'rls'

### ISSUE THREAD

**Issue by patriksvensson** [rust-lang-nursery/rls-vscode#311] opened 2018-05-11 08:13 UTC
I noticed that the Rust VS Code plugin suddenly was building using the `debug` target which gave a lot of conflicts when switching between VS Code and the command line and also led to a lot of non-incremental rebuilds for some reason.

By setting the `rust.target` configuration to `rls` I got it working again (see picture).

![image](https://user-images.githubusercontent.com/357872/39913839-85384baa-5503-11e8-97a3-a853ec663009.png)

Not sure if I messed something up or if this is a regression in the plugin, so feel free to close this issue if you suspect the former.

**Rust VS code version:** `0.4.2`
**RLS version:** `rls-preview 0.126.0-stable (f5a0c91 2018-03-26)`

**Comment by Xanewok** [comment] 2018-05-11 12:45
Which RLS version are you using?

**Comment by patriksvensson** [comment] 2018-05-11 12:54
@Xanewok 

**Rust VS code version:** `0.4.2`
**RLS version:** `rls-preview 0.126.0-stable (f5a0c91 2018-03-26)`

Updated the issue body as well with this information.

**Comment by Xanewok** [comment] 2018-05-11 13:03
@patriksvensson that'd be on me - I introduced this bug and fixed it on Mar 29th (https://github.com/rust-lang-nursery/rls/pull/793), so this should be fixed in newer versions =)

There is a single RLS version associated with a stable Rust release, so one workaround might be to set default "rust.target" to "rls" for now in the extension. @nrc what do you think?

**Comment by Xanewok** [comment] 2018-05-11 13:06
@patriksvensson wait, setting `rust.target` fixed that? Shouldn't setting `rust.target_dir` be correct in this case?

**Comment by patriksvensson** [comment] 2018-05-11 13:06
@Xanewok Correct, setting `rust.target` fixed that for me.

**Comment by Xanewok** [comment] 2018-05-11 13:07
That's... unexpected! I'll look into that, thanks for reporting it.

**Comment by patriksvensson** [comment] 2018-05-11 13:08
@Xanewok Hold on. I just verified and it creates the `rls/debug` folder but there's only a cargo.lock in there so it might not have solved it after all. Experienced no more problems after the fix though. Will try target_dir and report back.

**Comment by patriksvensson** [comment] 2018-05-11 13:18
@Xanewok Setting `rust.target_dir` does nothing. I tried setting it to `rls`, but it still creates a `debug` folder. Tried setting the `rust.target` to `rls` as well, but that only creates the `rls/debug` folder with a `cargo.lock` file.

I deleted the target directory between changes and restarted VS code to make sure that nothing else was interfering with the results.

**Comment by AlexEne** [comment] 2018-05-14 21:35
Just so I understand, the correct behavior is to have my_project/rls/debug and my_project/target/debug ?
Wouldn't target/rls have been a nicer option since that folder is already ignored by the default .gitignore ?

**Comment by Xanewok** [comment] 2018-05-15 08:52
@AlexEne it definitely would have, it was mistake on my part. Merged fix in #316.

I'll close the issue, since this should be definitely resolved now.

⚠️  For anyone still encountering the issue, be sure to specify `"rust.target_dir": "target/rls"` in the User Settings for the time being, this should be resolved when a new version of the extension is published to the marketplace.

**Closed by Xanewok** 2018-05-15 08:52 UTC

**Comment by scottjmaddox** [comment] 2018-05-16 15:58
Setting target_dir is working as a workaround in one project, but not in another. It is working a project with a cargo workspace, though I'm not sure if that's the root cause of the difference.
